from sqlmodel import Session
from models import *
from database import engine, create_db_and_tables

def create_samples():
    with Session(engine) as session:
        artist_hendrix = Artist(name="Jimmy Hendrix", real_name="James Marshall Hendrix", age=27, genre="Rock")
        artist_future = Artist(name="Future", real_name="Nayvadius DeMun Cash", age=41, genre="Hip-Hop/Rap")
        artist_pinkpantheress = Artist(name="PinkPantheress", real_name="Victoria Beverley Walker", age=24, genre="Pop/Electronic")
        artist_bowie = Artist(name="David Bowie", real_name="David Robert Jones", age=69, genre="Rock")
        artist_marley = Artist(name="Bob Marley", real_name="Robert Nesta Marley", age=36, genre="Reggae")
        artist_whitney = Artist(name="Whitney Houston", real_name="Whitney Elizabeth Houston", age=48, genre="R&B/Pop")
        artist_kendrick = Artist(name="Kendrick Lamar", real_name="Kendrick Lamar Duckworth", age=37, genre="Hip-Hop")
        artist_adele = Artist(name="Adele", real_name="Adele Laurie Blue Adkins", age=36, genre="Pop/Soul")
        artist_elton = Artist(name="Elton John", real_name="Reginald Kenneth Dwight", age=77, genre="Pop/Rock")
        artist_lizzo = Artist(name="Lizzo", real_name="Melissa Viviane Jefferson", age=36, genre="Pop/R&B")
        artist_billie = Artist(name="Billie Eilish", real_name="Billie Eilish Pirate Baird O'Connell", age=23, genre="Alternative Pop")
        artist_ariana = Artist(name="Ariana Grande", real_name="Ariana Grande-Butera", age=31, genre="Pop/R&B")
        artist_weeknd = Artist(name="The Weeknd", real_name="Abel Makkonen Tesfaye", age=34, genre="R&B/Pop")
        artist_drake = Artist(name="Drake", real_name="Aubrey Drake Graham", age=37, genre="Hip-Hop/R&B")
        artist_taylor = Artist(name="Taylor Swift", real_name="Taylor Alison Swift", age=34, genre="Pop/Country")
        artist_bruno = Artist(name="Bruno Mars", real_name="Peter Gene Hernandez", age=39, genre="Pop/R&B")
        artist_rihanna = Artist(name="Rihanna", real_name="Robyn Rihanna Fenty", age=36, genre="Pop/R&B")
        artist_bad_bunny = Artist(name="Bad Bunny", real_name="Benito Antonio Martínez Ocasio", age=30, genre="Reggaeton/Latin Trap")
        artist_rosalia = Artist(name="Rosalía", real_name="Rosalía Vila Tobella", age=31, genre="Flamenco Pop")
        artist_metro = Artist(name="Metro Boomin", real_name="Leland Tyler Wayne", age=31, genre="Hip-Hop Production")


        festival_rockinrio = Festival(name="Rock In Rio", crowd_capacity=40000, start_date=date(2025,9,13), end_date=date(2025,9,22), location="Rio de Janeiro, Brazil", artists=[artist_hendrix, artist_future, artist_pinkpantheress, artist_bowie, artist_marley])
        festival_primaverasound = Festival(name="Primavera Sound", crowd_capacity=85000, start_date=date(2025,6,4), end_date=date(2025,6,8), location="Barcelona, Spain", artists=[artist_whitney, artist_kendrick, artist_adele, artist_elton, artist_lizzo])
        festival_tomorrowland = Festival(name="Tomorrowland", crowd_capacity=200000, start_date=date(2025,10,10), end_date=date(2025,10,12), location ="Boom, Belgium", artists=[artist_billie, artist_ariana, artist_weeknd, artist_drake, artist_taylor])
        festival_coachella = Festival(name="Coachella", crowd_capacity=125000, start_date=date(2025, 4, 11), end_date=date(2025, 4, 20), location="Indio, California, USA", artists=[artist_bruno, artist_rihanna, artist_bad_bunny, artist_rosalia, artist_metro])
        festival_glastonbury = Festival(name="Glastonbury", crowd_capacity=210000, start_date=date(2025, 6, 25), end_date=date(2025, 6, 29), location="Pilton, Somerset, UK", artists=[artist_hendrix, artist_future, artist_pinkpantheress, artist_bowie, artist_marley])
        festival_lollapalooza = Festival(name="Lollapalooza", crowd_capacity=100000, start_date=date(2025, 7, 31), end_date=date(2025, 8, 3), location="Chicago, Illinois, USA", artists=[artist_whitney, artist_kendrick, artist_adele, artist_elton, artist_lizzo])
        festival_sziget = Festival(name="Sziget Festival", crowd_capacity=90000, start_date=date(2025, 8, 6), end_date=date(2025, 8, 13), location="Budapest, Hungary", artists=[artist_billie, artist_ariana, artist_weeknd, artist_drake, artist_taylor])
        festival_ultra = Festival(name="Ultra Music Festival", crowd_capacity=55000, start_date=date(2025, 3, 28), end_date=date(2025, 3, 30), location="Miami, Florida, USA", artists=[artist_bruno, artist_rihanna, artist_bad_bunny, artist_rosalia, artist_metro])
        festival_edc = Festival(name="Electric Daisy Carnival", crowd_capacity=150000, start_date=date(2025, 5, 16), end_date=date(2025, 5, 18), location="Las Vegas, Nevada, USA", artists=[artist_hendrix, artist_future, artist_pinkpantheress, artist_bowie, artist_marley])
        festival_reading = Festival(name="Reading Festival", crowd_capacity=105000, start_date=date(2025, 8, 22), end_date=date(2025, 8, 24), location="Reading, Berkshire, UK", artists=[artist_whitney, artist_kendrick, artist_adele, artist_elton, artist_lizzo])
        festival_bonnaroo = Festival(name="Bonnaroo", crowd_capacity=80000, start_date=date(2025, 6, 12), end_date=date(2025, 6, 15), location="Manchester, Tennessee, USA", artists=[artist_billie, artist_ariana, artist_weeknd, artist_drake, artist_taylor])
        festival_sxsw = Festival(name="SXSW", crowd_capacity=300000, start_date=date(2025, 3, 14), end_date=date(2025, 3, 22), location="Austin, Texas, USA", artists=[artist_bruno, artist_rihanna, artist_bad_bunny, artist_rosalia, artist_metro])
        festival_woodstock = Festival(name="Woodstock", crowd_capacity=400000, start_date=date(2025, 8, 15), end_date=date(2025, 8, 17), location="Bethel, New York, USA", artists=[artist_hendrix, artist_future, artist_pinkpantheress, artist_bowie, artist_marley])
        festival_exit = Festival(name="Exit Festival", crowd_capacity=60000, start_date=date(2025, 7, 10), end_date=date(2025, 7, 13), location="Novi Sad, Serbia", artists=[artist_whitney, artist_kendrick, artist_adele, artist_elton, artist_lizzo])
        festival_afropunk = Festival(name="Afropunk Festival", crowd_capacity=70000, start_date=date(2025, 8, 23), end_date=date(2025, 8, 24), location="Brooklyn, New York, USA", artists=[artist_billie, artist_ariana, artist_weeknd, artist_drake, artist_taylor])
        festival_fuji_rock = Festival(name="Fuji Rock Festival", crowd_capacity=50000, start_date=date(2025, 7, 25), end_date=date(2025, 7, 27), location="Niigata Prefecture, Japan", artists=[artist_bruno, artist_rihanna, artist_bad_bunny, artist_rosalia, artist_metro])
        festival_mawazine = Festival(name="Mawazine Festival", crowd_capacity=250000, start_date=date(2025, 6, 20), end_date=date(2025, 6, 28), location="Rabat, Morocco", artists=[artist_hendrix, artist_future, artist_pinkpantheress, artist_bowie, artist_marley])
        festival_sonar = Festival(name="Sónar Festival", crowd_capacity=120000, start_date=date(2025, 6, 13), end_date=date(2025, 6, 15), location="Barcelona, Spain", artists=[artist_whitney, artist_kendrick, artist_adele, artist_elton, artist_lizzo])
        festival_outsidelands = Festival(name="Outside Lands", crowd_capacity=75000, start_date=date(2025, 8, 8), end_date=date(2025, 8, 10), location="San Francisco, California, USA", artists=[artist_billie, artist_ariana, artist_weeknd, artist_drake, artist_taylor])
        festival_pitchfork = Festival(name="Pitchfork Music Festival", crowd_capacity=20000, start_date=date(2025, 7, 18), end_date=date(2025, 7, 20), location="Chicago, Illinois, USA", artists=[artist_bruno, artist_rihanna, artist_bad_bunny, artist_rosalia, artist_metro])


        session.add(festival_rockinrio)
        session.add(festival_primaverasound)
        session.add(festival_tomorrowland)
        session.add(festival_coachella)
        session.add(festival_glastonbury)
        session.add(festival_lollapalooza)
        session.add(festival_sziget)
        session.add(festival_ultra)
        session.add(festival_edc)
        session.add(festival_reading)
        session.add(festival_bonnaroo)
        session.add(festival_sxsw)
        session.add(festival_woodstock)
        session.add(festival_exit)
        session.add(festival_afropunk)
        session.add(festival_fuji_rock)
        session.add(festival_mawazine)
        session.add(festival_sonar)
        session.add(festival_outsidelands)
        session.add(festival_pitchfork)

        session.commit()

        session.refresh(festival_rockinrio)
        session.refresh(festival_primaverasound)
        session.refresh(festival_tomorrowland)
        session.refresh(festival_coachella)
        session.refresh(festival_glastonbury)
        session.refresh(festival_lollapalooza)
        session.refresh(festival_sziget)
        session.refresh(festival_ultra)
        session.refresh(festival_edc)
        session.refresh(festival_reading)
        session.refresh(festival_bonnaroo)
        session.refresh(festival_sxsw)
        session.refresh(festival_woodstock)
        session.refresh(festival_exit)
        session.refresh(festival_afropunk)
        session.refresh(festival_fuji_rock)
        session.refresh(festival_mawazine)
        session.refresh(festival_sonar)
        session.refresh(festival_outsidelands)
        session.refresh(festival_pitchfork)

        

        print("Created artist:", artist_hendrix)
        print("Created artist:", artist_future)
        print("Created artist:", artist_pinkpantheress)
        print("Created artist:", artist_bowie)
        print("Created artist:", artist_marley)
        print("Created artist:", artist_whitney)
        print("Created artist:", artist_kendrick)
        print("Created artist:", artist_adele)
        print("Created artist:", artist_elton)
        print("Created artist:", artist_lizzo)
        print("Created artist:", artist_billie)
        print("Created artist:", artist_ariana)
        print("Created artist:", artist_weeknd)
        print("Created artist:", artist_drake)
        print("Created artist:", artist_taylor)
        print("Created artist:", artist_bruno)
        print("Created artist:", artist_rihanna)
        print("Created artist:", artist_bad_bunny)
        print("Created artist:", artist_rosalia)
        print("Created artist:", artist_metro)

        print("Created festival:", festival_rockinrio)
        print("Created festival:", festival_primaverasound)
        print("Created festival:", festival_tomorrowland)
        print("Created festival:", festival_coachella)
        print("Created festival:", festival_glastonbury)
        print("Created festival:", festival_lollapalooza)
        print("Created festival:", festival_sziget)
        print("Created festival:", festival_ultra)
        print("Created festival:", festival_edc)
        print("Created festival:", festival_reading)
        print("Created festival:", festival_bonnaroo)
        print("Created festival:", festival_sxsw)
        print("Created festival:", festival_woodstock)
        print("Created festival:", festival_exit)
        print("Created festival:", festival_afropunk)
        print("Created festival:", festival_fuji_rock)
        print("Created festival:", festival_mawazine)
        print("Created festival:", festival_sonar)
        print("Created festival:", festival_outsidelands)
        print("Created festival:", festival_pitchfork)


def main():
    create_db_and_tables()
    create_samples()


if __name__ == "__main__":
    main()
